name: conny
description: Simple Console library
version: 1.0.0
homepage: https://github.com/Downmoto/conny

publish_to: pub.dev

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
